# GitHub Pages Configuration
theme: jekyll-theme-minimal
title: Ryan's Cookbook
description: I cook these things. Now you can.

# Remove GitHub project link and profile
show_downloads: false
github:
  is_project_page: false
  is_user_page: false

# Better markdown processing
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-relative-links
  - jemoji

relative_links:
  enabled: true
  collections: true
