# GitHub Pages Configuration
theme: jekyll-theme-minimal
title: Ryan's Cookbook
description: Make some food, idiot. 

# Remove GitHub project link
show_downloads: false
github:
  is_project_page: false
  is_user_page: false

# Markdown processing - this should fix link issues
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# Plugin configuration
plugins:
  - jekyll-relative-links
  - jemoji
  - jekyll-seo-tag

# Relative links configuration
relative_links:
  enabled: true
  collections: true

# Include these files
include:
  - README.md
  - "*/**.md"
