# GitHub Pages Configuration with Cayman Theme
theme: jekyll-theme-cayman
title: Ryan's Cookbook
description: Make some food, idiot. 

# Hide GitHub link
github:
  is_project_page: false

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
